diyblog/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs', views.BlogPostListView.as_view(), name='blogs'),
    path('<int:blog_id>/', views.blog_detail, name='blog-detail'),
    path('bloggers', views.AuthorListView.as_view(), name='bloggers'),
    path('blogger/<int:author_id>/', views.author_detail, name='blogger'),
    path('<int:blog_id>/create/', views.add_comment, name='create')
    #path('blog/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
]

diyblog/diyblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='blog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

diyblog/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Used in /admin site


class Comment(models.Model):
    """Model representing a blog comment."""
    comment = models.CharField(max_length=200, help_text='Enter a comment', blank=False)
    blog = models.ForeignKey('BlogPost', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    
    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.comment


class Author(models.Model):
    name = models.CharField(max_length=50, help_text='Enter author name')
    bio = models.TextField(help_text='Enter bio')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('blogger', args=[str(self.id)])


class BlogPost(models.Model):
    # Fields
    title = models.CharField(max_length=100, help_text='Enter title')
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, related_name='blogposts')
    description = models.TextField(help_text='Description')
    
    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog-detail', args=[str(self.id)])
    

diyblog/blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']  # Dodaj tutaj pola, które chcesz uwzględnić

diyblog/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Author, BlogPost, Comment
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import CommentForm
from django.http import HttpResponse


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_blogposts = BlogPost.objects.all().count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    context = {
        'num_authors': num_authors,
        'num_blogposts': num_blogposts,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class BlogPostListView(generic.ListView):
    model = BlogPost
    # context_object_name = 'book_list'   # your own name for the list as a template variable
    paginate_by = 4
    
class AuthorListView(generic.ListView):
    model = Author
    
def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'blogger.html', {'author': author})

def blog_detail(request, blog_id):
    blog = BlogPost.objects.get(pk=blog_id)
    return render(request, 'blog-detail.html', {'blog': blog})


@login_required
def add_comment(request, blog_id):
    blog_post = get_object_or_404(BlogPost, pk=blog_id)
    print('blog id ' , blog_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.blog = blog_post
            comment.save()
            return redirect(blog_post.get_absolute_url())
    else:
        form = CommentForm()

    return render(request, 'create-comment.html', {'form': form})

diyblog/blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Blog</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous" />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'blogs' %}">All Blog Posts</a></li>
              <li><a href="{% url 'bloggers' %}">All Authors</a></li>
              {% if user.is_authenticated %}
              <br>
              <li><a>Hi {{ user.username }}!</li></a>
              <li><a href="{% url 'logout' %}">Logout</a></li>
              {% else %}
              <br>
              <li><a>You are not logged in</a></li>
              <li><a href="{% url 'login' %}">Log In</a></li>
              {% endif %}

            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}
          {% block pagination %}
            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

diyblog/blog/templates/blog-detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ blog.title }}</h1>
  <p><h4>Post date:</h4> {{blog.date}}</p>
  <p><h4>Author:</h4> {{blog.author}}</p>
  <p><h4>Description:</h4> {{blog.description}}</p>
  <pre><h3>Comments:</h3></pre>
  {% for comment in blog.comment_set.all%}
  <p>Comment Author (not implemented yet) {{comment.date}} - {{comment.comment}}</p>
  {% endfor %}
  {% if user.is_authenticated %}
  
  <a href='{% url 'create' blog.id%}'>Add a comment</a>
  {% endif %}
{% endblock %}

diyblog/blog/templates/blog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Authors List</h1>
  <!-- <the model name>_list -->
  {% if author_list %}
    <ul>
      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.name }}</a>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no authors.</p>
  {% endif %}
{% endblock %}

diyblog/blog/templates/blog/blogpost_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blog List</h1>
  <!-- <the model name>_list -->
  {% if blogpost_list %}
    <ul>
      {% for blog in blogpost_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>
        ({{blog.author}})
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no blogs.</p>
  {% endif %}
{% endblock %}

diyblog/blog/templates/blogger.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blogger: {{ author.name }}</h1>
  <p><h2>Bio</h2></p>
  <p>{{ author.bio }}</p>
  <h2>Blogs list</h2>
  <ul>
    {% for blogpost in author.blogposts.all %}
      <li>{{ blogpost.title }} ({{blogpost.date}})</li>
    {% endfor %}
  </ul>
{% endblock %}

diyblog/blog/templates/create-comment.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.comment.label_tag }}
    {{ form.comment.errors }}
    <textarea class="comment-field" id="{{ form.comment.id_for_label }}" name="{{ form.comment.name }}" rows="4">{{ form.comment.value }}</textarea>
    <button type="submit">Submit</button>
</form>
{% endblock %}

diyblog/blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Mini-blog site!</h1>
  <p>
    Welcome to our blog, a website developed by
    <em>Adam</em>!
  </p>
  <h2>Dynamic content</h2>
  <p>Our blog has the following record counts:</p>
  <ul>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Blogs:</strong> {{ num_blogposts }}</li>
  </ul>
{% endblock %}